apiVersion: apps/v1
kind: Deployment	#Kubernates resource kind we are creating
metadata:
  name: spring-docker-kuber-jenkins
spec:
  selector:
    matchLabels:
      app: spring-docker-kuber-jenkins
  replicas: 3	# no of replics that we will be create for deployment
  template:
    metadata:
      labels:
        app: spring-docker-kuber-jenkins
    spec:
      containers:
        - name: spring-docker-kuber-jenkins
          image: sagarlucky/devops-pro	# image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080	# the port the container is running on in the cluster
            
---         
            
            
apiVersion: v1	#kubernates API version
kind: Service	#kubernates resource kind we are creating
metadata:	#metadata of resource kind we are creating
  name: spring-docker-kube-jenkins-svc
spec:
  selector:
    app: spring-docker-kuber-jenkins
  ports:
    - protocol: "TCP"
      port: 8080	# the port that service running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: NodePort # type of the service

