---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-docker-kuber-jenkins
spec:
  selector:
    matchLabels:
      app: spring-docker-kuber-jenkins
  replicas: 3
  template:
    metadata:
      labels:
        app: spring-docker-kuber-jenkins
    spec:
      containers:
        - name: spring-docker-kuber-jenkins
          image: sagarlucky/devops-pro  # Corrected: removed unnecessary tab characters
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: spring-docker-kube-jenkins-svc
spec:
  selector:
    app: spring-docker-kuber-jenkins
  ports:
    - protocol: TCP  # Corrected: protocol should be in lowercase
      port: 8080
      targetPort: 8080
  type: NodePort
